kubernetes-ingress:
  controller:
    kubernetesGateway:
      enabled: true
      gatewayControllerName: haproxy.org/gateway-controller

    service:
      type: LoadBalancer
      tcpPorts:
        - name: pacmantcp
          protocol: TCP
          port: 8080
          targetPort: 80
