haproxy-ingress:
  controller:
    kubernetesGateway:
      enabled: true
      gatewayControllerName: haproxy.org/gateway-controller
    service:
      tcpPorts:
        - name: listener1
          protocol: TCP
          port: 8000
          targetPort: 8000
