---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-gateway
spec:
  gatewayClassName: nginx
  listeners:
    - name: http-listener
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
    - name: http-listener2
      port: 8080
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
    - name: argocd-listener
      port: 443
      protocol: HTTPS
      hostname: "argocd.dvoc24.v3nc.org"
      allowedRoutes:
        namespaces:
          from: All
      tls:
        certificateRefs:
        - kind: Secret
          group: ""
          name: argocd-dvoc24-v3nc-org
    - name: pacman-listener
      port: 443
      protocol: HTTPS
      hostname: "pacman.dvoc24.v3nc.org"
      allowedRoutes:
        namespaces:
          from: All
      tls:
        certificateRefs:
        - kind: Secret
          group: ""
          name: pacman-dvoc24-v3nc-org
        mode: Terminate
