---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway
  annotations:
    cert-manager.io/cluster-issuer: selfsigned-issuer
spec:
  gatewayClassName: nginx
  listeners:
    - name: http-listener
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
    - name: argocd-listener
      port: 443
      protocol: HTTPS
      hostname: "argocd.demo"
      allowedRoutes:
        namespaces:
          from: All
      tls:
        certificateRefs:
        - kind: Secret
          group: ""
          name: argocd-demo
    - name: pacman-listener
      port: 443
      protocol: HTTPS
      hostname: "pacman.demo"
      allowedRoutes:
        namespaces:
          from: All
      tls:
        certificateRefs:
        - kind: Secret
          group: ""
          name: pacman-demo
        mode: Terminate
