{{- if .Capabilities.APIVersions.Has "gateway.networking.k8s.io/v1alpha3" }}
---
apiVersion: gateway.networking.k8s.io/v1alpha3
kind: BackendTLSPolicy
metadata:
  name: argocd-server
spec:
  targetRefs:
  - group: ''
    kind: Service
    name: argocd-server
  validation:
    caCertificateRefs:
      - group: ''
        kind: ConfigMap
        name: ca
    hostname: argocd.dvoc24.v3nc.org
{{- end }}
