{{- if eq "gateway-haproxy" .Values.targetRevision }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-haproxy
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: gateway-haproxy
    server: https://kubernetes.default.svc
  project: default
  revisionHistoryLimit: 10
  source:
    path: gateway-haproxy
    repoURL: https://github.com/venc0r/devopscamp2024.git
    targetRevision: {{ .Values.targetRevision }}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
{{- end }}
