{{- if and( .Capabilities.APIVersions.Has "gateway.networking.k8s.io/v1" .Values.enableGateway ) }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd-server
spec:
  parentRefs:
    - name: gateway
      namespace: gateway-envoy
  hostnames:
    - argocd.demo
  rules:
    - backendRefs:
        - name: argocd-server
          port: 443
{{- end }}
