{{- if and (.Capabilities.APIVersions.Has "gateway.networking.k8s.io/v1") .Values.enableGateway }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: pacman.demo
spec:
  parentRefs:
    - name: gateway
      namespace: gateway-envoy
  hostnames:
    - pacman.demo
  rules:
    - backendRefs:
        - name: pacman
          port: 80

{{- end }}
