{{- if .Capabilities.APIVersions.Has "gateway.networking.k8s.io/v1" }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: pacman.dvoc24.v3nc.org
spec:
  parentRefs:
    - name: gateway
      namespace: gateway-traefik
  hostnames:
    - pacman.dvoc24.v3nc.org
  rules:
    - backendRefs:
        - name: pacman
          port: 80

{{- end }}
