apiVersion: v2
name: gateway-traefik
description: traefik argocd app chart
type: application
version: 0.0.1

dependencies:
- name: traefik
  version: 32.1.0
  repository: https://traefik.github.io/charts
