traefik:
  gateway:
    enabled: false
  service:
    enabled: false
  providers:
    kubernetesGateway:
      enabled: true
    kubernetesCRD:
      enabled: false
    kubernetesIngress:
      enabled: false
