---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: gateway
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-gateway
spec:
  gatewayClassName: haproxy-gatewayclass
  listeners:
    - name: tcp-listener
      port: 80
      protocol: TCP
      allowedRoutes:
        namespaces:
          from: All
