nginx-gateway-fabric:
  service:
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
    - name: http2
      port: 8080
      protocol: TCP
      targetPort: 8080
