argo-cd:
  server:
    ingress:
      enabled: true
      https: false
      ingressClassName: nginx
      hostname: argocd.dvoc24.v3nc.org
      annotations:
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        cert-manager.io/cluster-issuer: letsencrypt-nginx
      extraTls:
        - secretName: argocd-cert
          hosts:
            - argocd.dvoc24.v3nc.org
