argo-cd:
  server:
    ingress:
      enabled: true
      https: false
      ingressClassName: nginx
      hostname: argocd.dvoc24.v3nc.org
      annotations:
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
