apiVersion: v2
name: ingress-nginx
description: ingress-nginx argocd app chart
type: application
version: 0.0.1

dependencies:
- name: ingress-nginx
  version: 4.11.2
  repository: https://kubernetes.github.io/ingress-nginx
