---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  labels:
    argocd.argoproj.io/instance: argocd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  revisionHistoryLimit: 10
  source:
    path: argocd
    repoURL: https://github.com/venc0r/devopscamp2024.git
    targetRevision: main
    helm:
      values: |
        enableGateway: false
        argo-cd:
          server:
            ingress:
              enabled: false
              hostname: argocd.demo
              annotations:
                cert-manager.io/cluster-issuer: selfsigned-issuer
              extraTls:
                - secretName: argocd-cert
                  hosts:
                    - argocd.demo
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
