---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-traefik
  labels:
    argocd.argoproj.io/instance: argocd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: gateway-traefik
    server: https://kubernetes.default.svc
  project: default
  revisionHistoryLimit: 10
  source:
    path: gateway-traefik
    repoURL: https://github.com/venc0r/devopscamp2024.git
    targetRevision: main
    helm:
      values: |
        traefik:
          gateway:
            enabled: true
            name: gateway
            annotations:
              cert-manager.io/cluster-issuer: selfsigned-issuer
            listeners:
              web:
                namespacePolicy: All
              argocd-listener:
                port: 8443
                protocol: HTTPS
                hostname: "argocd.demo"
                namespacePolicy: All
                certificateRefs:
                - kind: Secret
                  group: ""
                  name: argocd-demo
                mode: Terminate
              pacman-listener:
                port: 8443
                protocol: HTTPS
                hostname: "pacman.demo"
                namespacePolicy: All
                certificateRefs:
                - kind: Secret
                  group: ""
                  name: pacman-demo
                mode: Terminate
          gatewayClass:
            enabled: true
          providers:
            kubernetesGateway:
              enabled: true
          logs:
            general:
              level: "DEBUG"
            access:
              enabled: true
              retryattempts: false
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
