---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pacman
  labels:
    argocd.argoproj.io/instance: argocd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: pacman
    server: https://kubernetes.default.svc
  project: default
  revisionHistoryLimit: 10
  source:
    path: pacman
    repoURL: https://github.com/venc0r/devopscamp2024.git
    targetRevision: main
    helm:
      values: |
        enableGateway: false
        pacman:
          mongodb:
            auth:
              rootPassword: stablePasswordForDemo
          ingress:
            create: true
            host: pacman.demo
            annotations:
              cert-manager.io/cluster-issuer: selfsigned-issuer
            tls:
              enabled: true
              secretName: pacman-cert
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
