---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-haproxy
  labels:
    argocd.argoproj.io/instance: argocd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: gateway-haproxy
    server: https://kubernetes.default.svc
  project: default
  revisionHistoryLimit: 10
  source:
    path: gateway-haproxy
    repoURL: https://github.com/venc0r/devopscamp2024.git
    targetRevision: main
    helm:
      values: |
        kubernetes-ingress:
          controller:
            kubernetesGateway:
              enabled: true
              gatewayControllerName: haproxy.org/gateway-controller
            service:
              type: LoadBalancer
              tcpPorts:
                - name: pacmantcp
                  protocol: TCP
                  port: 8080
                  targetPort: 80
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
