---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-haproxy
  labels:
    argocd.argoproj.io/instance: argocd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: ingress-haproxy
    server: https://kubernetes.default.svc
  project: default
  revisionHistoryLimit: 10
  source:
    path: ingress-haproxy
    repoURL: https://github.com/venc0r/devopscamp2024.git
    targetRevision: main
    helm:
      values: |
        kubernetes-ingress:
          controller:
            service:
              type: LoadBalancer
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
