apiVersion: v2
name: cert-manager
description: A Helm chart for a cert-manager

type: application
version: 0.0.1
dependencies:
- name: cert-manager
  version: v1.17.1
  repository: https://charts.jetstack.io
